In [1]:
import numpy as np

In [2]:
training_data = np.load('fulldataset-song-artist-train_data_XL.npz')

In [3]:
training_data

In [4]:
print(training_data.files)

['x', 'y', 'mask', 'seq_len', 'num_groups']


In [7]:
print(training_data['x'].shape, training_data['x'].dtype)
print(training_data['y'].shape, training_data['y'].dtype)
print(training_data['mask'].shape, training_data['mask'].dtype)
print(training_data['seq_len'].shape, training_data['seq_len'].dtype)
print(training_data['num_groups'].shape, training_data['num_groups'].dtype)

(19930, 40, 512) float64
(19930, 40, 512) float64
(19930, 40, 512) float64
(19930,) int64
(19930,) int64


In [10]:
IDX = 25
print(training_data['x'][IDX])
print(training_data['y'][IDX])
print(training_data['mask'][IDX])
print(training_data['seq_len'][IDX])
print(training_data['num_groups'][IDX])

[[0.000e+00 2.425e+03 4.760e+02 ... 7.870e+02 6.520e+02 0.000e+00]
 [4.000e+00 7.580e+02 5.890e+02 ... 7.870e+02 6.520e+02 1.000e+00]
 [4.000e+00 3.000e+01 3.800e+01 ... 0.000e+00 6.910e+02 1.000e+01]
 ...
 [6.200e+01 9.000e+00 1.000e+00 ... 4.410e+02 4.410e+02 4.410e+02]
 [4.410e+02 4.410e+02 4.410e+02 ... 4.410e+02 4.410e+02 4.410e+02]
 [4.410e+02 4.410e+02 4.410e+02 ... 4.410e+02 4.410e+02 4.410e+02]]
[[2.425e+03 4.760e+02 9.740e+02 ... 6.520e+02 0.000e+00 4.000e+00]
 [7.580e+02 5.890e+02 5.820e+02 ... 6.520e+02 1.000e+00 4.000e+00]
 [3.000e+01 3.800e+01 7.580e+02 ... 6.910e+02 1.000e+01 0.000e+00]
 ...
 [9.000e+00 1.000e+00 3.400e+01 ... 4.410e+02 4.410e+02 4.410e+02]
 [4.410e+02 4.410e+02 4.410e+02 ... 4.410e+02 4.410e+02 4.410e+02]
 [4.410e+02 4.410e+02 4.410e+02 ... 4.410e+02 4.410e+02 4.410e+02]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
19306
38
